config/routes.rb
IwarksnsBase::Application.routes.draw do
  root 'posts#index', constraints: -> (r) { !r.session[:user_id].blank? }
  root 'welcome#index', as: :anonymous_root

  resources :users, only: [:index, :create] do
    member do
      post 'friend', to: :friend
      delete 'friend', to: :unfriend
    end
  end
  resources :posts, only: [:index, :create, :destroy]

  post 'sessions', to: 'sessions#create'
  delete 'sessions', to: 'sessions#destroy'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class Post < ActiveRecord::Base
  validates :body, presence: true

  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  has_secure_password
  validates :name, :email, presence: true

  has_and_belongs_to_many :friends, join_table: 'friendships',
                                    class_name: 'User',
                                    association_foreign_key: 'friend_id'

  has_many :posts
  has_many :comments

  before_create :initialize_token!

  def owns_post?(post)
    posts.where(id: post.id).exists?
  end

  def owns_comment?(comment)
    comments.where(id: comment.id).exists?
  end

  def friend?(user)
    friends.where(id: user.id).exists?
  end

  def initialize_token!
    return unless self.token.nil?
    self.token = loop do
      token = SecureRandom.urlsafe_base64(20, false)
      break token unless User.exists?(token: token)
    end
    self.save!
  end

  def become_friend(friend)
    User.transaction do
      self.friends << friend
      friend.friends << self
    end
  end

  def remove_friend(friend)
    User.transaction do
      self.friends.delete(friend)
      friend.friends.delete(self)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :set_new_user

  helper_method :current_user
  helper_method :user_signed_in?

  private

  def user_signed_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    redirect_to anonymous_root_path unless user_signed_in?
  end

  def login(user)
    session[:user_id] = user.id
  end

  def set_new_user
    @user = User.new unless user_signed_in?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.new
    @posts = Post.all
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path, notice: 'Post created'
    else
      render :index
    end
  end

  def destroy
  end

  private
  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!, only:[:create]

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user.try(:authenticate, params[:user][:password])
      login(@user)
      redirect_to root_path
    else
      @user = User.new
      @user.errors.add(:base, 'errors.login')
      @new_user = User.new
      render 'welcome/index'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to anonymous_root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only:[:create]
  before_action :set_user, except: [:index, :create]

  def index
    @users = User.all
  end

  def create
    @new_user = User.new(user_params)
    if @new_user.save
      login(@new_user)
      redirect_to root_path
    else
      render 'welcome/index'
    end
  end

  def friend
    current_user.add_friend(@user) unless current_user.friend?(@user)
    redirect_to :back
  end

  def unfriend
    current_user.remove_friend(@user) if current_user.friend?(@user)
    redirect_to :back
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def set_user
      @user = User.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :check_welcome_logined, only:[:index]

  def index
    @new_user = User.new
  end

  private
    def check_welcome_logined
      redirect_to root_path if user_signed_in?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to t('general.title'), root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to t('general.home'), root_path %></li>
          <li><%= link_to 'ユーザ一覧', users_path %></li>
          <li><%= link_to t('btn.logout'), sessions_path, method: :delete %></li>
        </ul>
      <% else %>
        <%= render 'sessions/form', user: user %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IwarksnsBase</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
  <%= render 'layouts/header', user: @user %>
  <%= yield %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for post, html: { class: 'form post-form' } do |f| %>
  <div class="form-group row">
    <div class="col-lg-11">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
    <div class="col-lg-1">
      <%= f.submit '投稿', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="row post">
  <span class="author">
    <%= post.user.name %>
  </span>
  <p>
    <%= post.body %>
  </p>
</div>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<% if @post.errors.any? %>
  <h2>エラー</h2>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'posts/form', post: @post %>

<div class="posts">
  <%= render @posts %>
</div>

app/views/users/_form.html.erb
<%= form_for user, html:{role:'form'} do |f| %>
  <% if user.errors.any? %>
    <div class="error_messages">
      <h2>エラー</h2>
      <ul>
        <% for message in user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email, 'メール' %>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード確認' %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div><%= f.submit t('btn.register'), class: "btn btn-primary" %></div>
<% end %>

app/views/users/_user.html.erb
<div class="row">
  <div class="col-xs-8">
    <%= user.name %>
  </div>
  <% if user_signed_in? && current_user.id != user.id %>
  <div class="col-xs-4">
    <% if current_user.friend?(user) %>
      <%= link_to '友達から外す', friend_user_path(user), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to '友達に追加', friend_user_path(user), method: :post, class: 'btn btn-primary' %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>ユーザ一覧</h1>
<%= render @users %>

app/views/welcome/index.html.erb
<h1>ぼくらのSNS</h1>
<p>ぼくらのSNSだよ。皆、参加してね。</p>

<hr>
<h2>ユーザー登録</h2>
<div class="col-xs-8 col-lg-8">
  <%= image_tag("study3.jpg", class: 'wide-img') %>
</div>
<div class="col-xs-4 col-lg-4">
  <%= render 'users/form', user: @new_user %>
</div>